"""Compatibility facade for the KORAIL Pydoll confirmation reader."""

from __future__ import annotations

from .korail_sidecar.pydoll import confirmation_reader as _owner

annotations = _owner.annotations
re = _owner.re
Callable = _owner.Callable
UTC = _owner.UTC
date = _owner.date
datetime = _owner.datetime
Protocol = _owner.Protocol
runtime_checkable = _owner.runtime_checkable
urlsplit = _owner.urlsplit
ZoneInfo = _owner.ZoneInfo
is_rate_limit_response = _owner.is_rate_limit_response
protection_trigger_from_http_response = _owner.protection_trigger_from_http_response
protection_trigger_from_text = _owner.protection_trigger_from_text
ReservationConfirmationTarget = _owner.ReservationConfirmationTarget
KORAIL_CONFIRMATION_SOURCE = _owner.KORAIL_CONFIRMATION_SOURCE
KORAIL_RESERVATION_LIST_SOURCE = _owner.KORAIL_RESERVATION_LIST_SOURCE
KorailSameSessionDetailEvidence = _owner.KorailSameSessionDetailEvidence
KorailConfirmationSnapshot = _owner.KorailConfirmationSnapshot
KorailConfirmationSession = _owner.KorailConfirmationSession
KorailReservationListSession = _owner.KorailReservationListSession
PaymentDeadlineParser = _owner.PaymentDeadlineParser
read_korail_same_session_confirmation = _owner.read_korail_same_session_confirmation
_session_is_authenticated = _owner._session_is_authenticated
_inconclusive_evidence = _owner._inconclusive_evidence
_blocked_evidence = _owner._blocked_evidence
_auth_required_evidence = _owner._auth_required_evidence
_is_complete_detail_evidence = _owner._is_complete_detail_evidence
_confirmation_snapshot_is_blocked = _owner._confirmation_snapshot_is_blocked
_confirmation_evidence_from_text = _owner._confirmation_evidence_from_text
_has_exact_train_number_marker = _owner._has_exact_train_number_marker
_has_exact_text_marker = _owner._has_exact_text_marker
_has_exact_route_markers = _owner._has_exact_route_markers
_reservation_date_markers = _owner._reservation_date_markers
_normalize_station = _owner._normalize_station
_parse_korail_payment_deadline = _owner._parse_korail_payment_deadline
