"""Compatibility facade for KORAIL station identity and official search bootstrap."""

from .provider_adapters import korail_search_bootstrap as _bootstrap
from .provider_registry import korail_search_contracts as _contracts
from .provider_registry import korail_search_url_policy as _url_policy

OFFICIAL_KORAIL_STATION_DATA_URL = _bootstrap.OFFICIAL_KORAIL_STATION_DATA_URL
OFFICIAL_KORAIL_RESULT_URL = _url_policy.OFFICIAL_KORAIL_RESULT_URL
MIN_STATION_COUNT = _bootstrap.MIN_STATION_COUNT
MAX_STATION_COUNT = _bootstrap.MAX_STATION_COUNT
STATION_REQUEST_TIMEOUT = _bootstrap.STATION_REQUEST_TIMEOUT
KorailStationIdentityUnavailable = _bootstrap.KorailStationIdentityUnavailable
KorailStationIdentity = _contracts.KorailStationIdentity
KorailStationIdentityCatalog = _bootstrap.KorailStationIdentityCatalog
KorailStationIdentityResolver = _bootstrap.KorailStationIdentityResolver
parse_korail_station_identities = _bootstrap.parse_korail_station_identities
build_korail_general_search_url = _url_policy.build_korail_general_search_url
validate_korail_general_search_url = _url_policy.validate_korail_general_search_url
