"""Compatibility model hub that eagerly registers canonical persistence owners."""

from .admin_auth import models as admin_auth_models
from .browser_companion import models as browser_companion_models
from .idempotency import models as idempotency_models
from .notification_management import models as notification_management_models
from .official_page_confirmation import models as official_page_confirmation_models
from .outbox_management import models as outbox_management_models
from .provider_account_management import models as provider_account_management_models
from .provider_circuit import models as provider_circuit_models
from .provider_execution import models as provider_execution_models
from .timetable_management import models as timetable_management_models
from .watch_management import models as watch_management_models

AdminAccount = admin_auth_models.AdminAccount
AdminSession = admin_auth_models.AdminSession
BrowserCompanionChallenge = browser_companion_models.BrowserCompanionChallenge
BrowserCompanionCredential = browser_companion_models.BrowserCompanionCredential
BrowserCompanionPairing = browser_companion_models.BrowserCompanionPairing
IdempotencyRecord = idempotency_models.IdempotencyRecord
KorailBrowserSeatSnapshot = browser_companion_models.KorailBrowserSeatSnapshot
KorailBrowserSnapshotBatch = browser_companion_models.KorailBrowserSnapshotBatch
NativePushCredential = notification_management_models.NativePushCredential
NativePushPairing = notification_management_models.NativePushPairing
NotificationChannel = notification_management_models.NotificationChannel
OfficialPageSeatConfirmation = official_page_confirmation_models.OfficialPageSeatConfirmation
OutboxEvent = outbox_management_models.OutboxEvent
ProviderCircuit = provider_circuit_models.ProviderCircuit
ProviderExecutionLease = provider_execution_models.ProviderExecutionLease
RailProviderAccount = provider_account_management_models.RailProviderAccount
ReservationAttempt = watch_management_models.ReservationAttempt
SeatObservation = watch_management_models.SeatObservation
StationCatalogCache = timetable_management_models.StationCatalogCache
TimetableSeatEvidence = timetable_management_models.TimetableSeatEvidence
Watch = watch_management_models.Watch
WatchCandidate = watch_management_models.WatchCandidate
WatchTransitionHistory = watch_management_models.WatchTransitionHistory
utcnow = watch_management_models.utcnow
