from __future__ import annotations

from . import official_rail_identity
from .admin_auth import schemas as admin_auth_schemas
from .browser_companion import schemas as browser_companion_schemas
from .event_stream import schemas as event_stream_schemas
from .health import schemas as health_schemas
from .notification_management import schemas as notification_management_schemas
from .observations.contracts import (
    ObservationErrorCategory as ObservationErrorCategory,
)
from .observations.contracts import (
    SeatObservationRequest as SeatObservationRequest,
)
from .observations.contracts import (
    SeatObservationResult as SeatObservationResult,
)
from .official_page_confirmation import schemas as official_page_confirmation_schemas
from .operation_summary import schemas as operation_summary_schemas
from .provider_account_management import schemas as provider_account_management_schemas
from .provider_registry import contracts as provider_registry_contracts
from .provider_registry.korail_search_url_policy import (
    validate_korail_general_search_url as validate_korail_general_search_url,
)
from .provider_registry.official_url_policy import (
    OFFICIAL_HOST_ROOTS as OFFICIAL_HOST_ROOTS,
)
from .provider_registry.official_url_policy import (
    is_official_provider_host as is_official_provider_host,
)
from .provider_schema_base import ProviderContractModel as ProviderContractModel
from .reservations.contracts import (
    ReservationProgressStage as ReservationProgressStage,
)
from .reservations.contracts import (
    ReservationProgressStageName as ReservationProgressStageName,
)
from .reservations.contracts import ReservationRequest as ReservationRequest
from .reservations.contracts import ReservationResult as ReservationResult
from .seat_status_operations import schemas as seat_status_operations_schemas
from .timetable_management import schemas as timetable_management_schemas
from .ui_preferences import schemas as ui_preferences_schemas
from .watch_management import provider_failure_policy as watch_provider_failure_policy
from .watch_management import schemas as watch_management_schemas

AuthStatus = admin_auth_schemas.AuthStatus
contains_protection_marker = official_rail_identity.contains_protection_marker
BrowserCompanionChallengeCreate = browser_companion_schemas.BrowserCompanionChallengeCreate
BrowserCompanionChallengeRead = browser_companion_schemas.BrowserCompanionChallengeRead
BrowserCompanionCredentialRead = browser_companion_schemas.BrowserCompanionCredentialRead
BrowserCompanionPairingCreate = browser_companion_schemas.BrowserCompanionPairingCreate
BrowserCompanionPairingExchange = browser_companion_schemas.BrowserCompanionPairingExchange
BrowserCompanionPairingRead = browser_companion_schemas.BrowserCompanionPairingRead
BrowserCompanionPairingResult = browser_companion_schemas.BrowserCompanionPairingResult
BrowserCompanionStatus = browser_companion_schemas.BrowserCompanionStatus
EventRead = event_stream_schemas.EventRead
KORAIL_BROWSER_COMPANION_SOURCE = browser_companion_schemas.KORAIL_BROWSER_COMPANION_SOURCE
KorailBrowserSeatStatus = browser_companion_schemas.KorailBrowserSeatStatus
KorailBrowserSnapshotCreate = browser_companion_schemas.KorailBrowserSnapshotCreate
KorailBrowserSnapshotRead = browser_companion_schemas.KorailBrowserSnapshotRead
KorailBrowserSnapshotRevision = browser_companion_schemas.KorailBrowserSnapshotRevision
KorailBrowserTrainSnapshot = browser_companion_schemas.KorailBrowserTrainSnapshot
LoginResult = admin_auth_schemas.LoginResult
UsernamePasswordCredentials = admin_auth_schemas.UsernamePasswordCredentials
OperationCurrentCounts = operation_summary_schemas.OperationCurrentCounts
OperationEntry = operation_summary_schemas.OperationEntry
OperationEntryKind = operation_summary_schemas.OperationEntryKind
OperationEntryLevel = operation_summary_schemas.OperationEntryLevel
OperationFreshness = operation_summary_schemas.OperationFreshness
OperationProviderCircuit = operation_summary_schemas.OperationProviderCircuit
OperationRate = operation_summary_schemas.OperationRate
OperationServiceState = operation_summary_schemas.OperationServiceState
OperationServiceStatus = operation_summary_schemas.OperationServiceStatus
OperationSourceFreshness = operation_summary_schemas.OperationSourceFreshness
OperationsSummary = operation_summary_schemas.OperationsSummary
OperationStatusCount = operation_summary_schemas.OperationStatusCount
OperationsWindow = operation_summary_schemas.OperationsWindow
OperationWindowCounts = operation_summary_schemas.OperationWindowCounts
OFFICIAL_PAGE_CONFIRMATION_SOURCE = (
    official_page_confirmation_schemas.OFFICIAL_PAGE_CONFIRMATION_SOURCE
)
OfficialPageSeatConfirmationCreate = (
    official_page_confirmation_schemas.OfficialPageSeatConfirmationCreate
)
OfficialPageSeatConfirmationItem = (
    official_page_confirmation_schemas.OfficialPageSeatConfirmationItem
)
OfficialPageSeatConfirmationItemRead = (
    official_page_confirmation_schemas.OfficialPageSeatConfirmationItemRead
)
OfficialPageSeatConfirmationRead = (
    official_page_confirmation_schemas.OfficialPageSeatConfirmationRead
)
OfficialPageSeatStatus = official_page_confirmation_schemas.OfficialPageSeatStatus
NotificationChannelCreate = notification_management_schemas.NotificationChannelCreate
NotificationChannelRead = notification_management_schemas.NotificationChannelRead
NotificationChannelUpdate = notification_management_schemas.NotificationChannelUpdate
normalize_official_train_number = official_rail_identity.normalize_official_train_number
QueuedResponse = notification_management_schemas.QueuedResponse
RailLoginMethod = provider_account_management_schemas.RailLoginMethod
RailProviderAccountRead = provider_account_management_schemas.RailProviderAccountRead
RailProviderAccountUpsert = provider_account_management_schemas.RailProviderAccountUpsert
RailProviderAuthStatus = provider_account_management_schemas.RailProviderAuthStatus
RailProviderRuntimeState = provider_account_management_schemas.RailProviderRuntimeState
RailProviderRuntimeStatusRead = provider_account_management_schemas.RailProviderRuntimeStatusRead
ProviderCapabilities = provider_registry_contracts.ProviderCapabilities
UiPreferencesRead = ui_preferences_schemas.UiPreferencesRead
UiPreferencesUpdate = ui_preferences_schemas.UiPreferencesUpdate
StationItem = timetable_management_schemas.StationItem
StationCatalog = timetable_management_schemas.StationCatalog
SeatStatusRefreshRequest = timetable_management_schemas.SeatStatusRefreshRequest
SeatAvailabilityStatus = timetable_management_schemas.SeatAvailabilityStatus
SeatAvailability = timetable_management_schemas.SeatAvailability
SeatAvailabilityNotObservedReason = timetable_management_schemas.SeatAvailabilityNotObservedReason
SeatAvailabilityProvenance = timetable_management_schemas.SeatAvailabilityProvenance
SeatAvailabilityAction = timetable_management_schemas.SeatAvailabilityAction
SeatClassAvailability = timetable_management_schemas.SeatClassAvailability
TimetableSeatEvidenceRead = timetable_management_schemas.TimetableSeatEvidenceRead
TimetableItem = timetable_management_schemas.TimetableItem
SeatStatusCooldownCause = seat_status_operations_schemas.SeatStatusCooldownCause
SeatStatusSourceStatus = seat_status_operations_schemas.SeatStatusSourceStatus
RegistrationEvidenceConflictDetail = watch_management_schemas.RegistrationEvidenceConflictDetail
WatchCandidateCreate = watch_management_schemas.WatchCandidateCreate
WatchCreate = watch_management_schemas.WatchCreate
WatchUpdate = watch_management_schemas.WatchUpdate
WatchCandidateLatestReservationAttemptRead = (
    watch_management_schemas.WatchCandidateLatestReservationAttemptRead
)
WatchCandidateRead = watch_management_schemas.WatchCandidateRead
WatchCandidateLatestObservationRead = watch_management_schemas.WatchCandidateLatestObservationRead
WatchRead = watch_management_schemas.WatchRead
ErrorPolicyResult = watch_provider_failure_policy.ErrorPolicyResult
HealthResponse = health_schemas.HealthResponse
